/* 
  This file was generated by KaRaMeL <https://github.com/FStarLang/karamel>
  KaRaMeL invocation: /home/eioannidis/karamel/krml -skip-compilation -skip-makefiles -skip-linking -bundle Pulse_Lib_RangeVec=Pulse.Lib.RangeVec,Pulse.Lib.Vector -warn-error -15-4-2 -tmpdir extraction/_c_output extraction/_output/Pulse_Lib_RangeVec.krml extraction/_output/Pulse_Lib_Vector.krml
  F* version: <unknown>
  KaRaMeL version: a4caa585
 */

#ifndef Pulse_Lib_RangeVec_H
#define Pulse_Lib_RangeVec_H

#include "krmllib.h"

typedef struct Pulse_Lib_RangeVec_range_s
{
  size_t start;
  size_t len;
}
Pulse_Lib_RangeVec_range;

extern Pulse_Lib_RangeVec_range Pulse_Lib_RangeVec_default_range;

typedef struct Pulse_Lib_Vector_vector_internal__Pulse_Lib_RangeVec_range_s
{
  Pulse_Lib_RangeVec_range *arr;
  size_t sz;
  size_t cap;
  Pulse_Lib_RangeVec_range default_val;
}
Pulse_Lib_Vector_vector_internal__Pulse_Lib_RangeVec_range;

typedef Pulse_Lib_Vector_vector_internal__Pulse_Lib_RangeVec_range
*Pulse_Lib_RangeVec_range_vec_t;

Pulse_Lib_Vector_vector_internal__Pulse_Lib_RangeVec_range
*Pulse_Lib_RangeVec_range_vec_create(void);

void
Pulse_Lib_RangeVec_range_vec_free(
  Pulse_Lib_Vector_vector_internal__Pulse_Lib_RangeVec_range *rv
);

size_t
Pulse_Lib_RangeVec_range_vec_contiguous_from(
  Pulse_Lib_Vector_vector_internal__Pulse_Lib_RangeVec_range *rv,
  size_t base
);

size_t
Pulse_Lib_RangeVec_range_vec_max_endpoint(
  Pulse_Lib_Vector_vector_internal__Pulse_Lib_RangeVec_range *rv
);

void
Pulse_Lib_RangeVec_vec_insert_at(
  Pulse_Lib_Vector_vector_internal__Pulse_Lib_RangeVec_range *rv,
  size_t i,
  Pulse_Lib_RangeVec_range r
);

void
Pulse_Lib_RangeVec_vec_remove_range(
  Pulse_Lib_Vector_vector_internal__Pulse_Lib_RangeVec_range *rv,
  size_t i,
  size_t count
);

void
Pulse_Lib_RangeVec_range_vec_add(
  Pulse_Lib_Vector_vector_internal__Pulse_Lib_RangeVec_range *rv,
  size_t offset,
  size_t len
);


#define Pulse_Lib_RangeVec_H_DEFINED
#endif /* Pulse_Lib_RangeVec_H */
