name: Build Steel Binaries for MacOS

on:
  workflow_dispatch:

jobs:

  build:

    runs-on: macos-latest

    steps:
    - name: Checkout Steel
      uses: actions/checkout@v3
      with:
        path: steel
