name: Build Pulse on Windows
on:
  workflow_dispatch:
jobs:
  build:
    runs-on: [self-hosted, windows, X64]
    steps:
      - name: Check out repo        
        uses: actions/checkout@v3
      - name: Build a package
        shell: C:\cygwin64\bin\bash.exe --login '{0}'
        run: |
          pulse/src/ci/package.sh -j 8 && echo "There is a CR at the end of this line"
      - name: Archive the package
        uses: actions/upload-artifact@v3
        with:
          name: pulse-Windows_x86_64.zip
          path: pulse\src\ci\pulse.zip
